# vim:set et ts=2 sts=2 sw=2 tw=0 fdm=marker:

[[plugins]]
repo = 'Shougo/ddu.vim'
hooks_file = '~/.config/nvim/config/plugins/plugins-ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-column-filename'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
